
    export const achievements= [
        "academic excellence",
        "sports achievements",
        "artistic accomplishments",
        "leadership roles",
        "community service awards",
        "public speaking awards",
        "scientific research awards",
        "literary awards",
        "musical achievements",
        "entrepreneurial ventures",
        "volunteer work",
        "internship experiences",
        "travel experiences",
        "cultural exchange programs",
        "hackathon wins",
        "coding competition wins",
        "robotics competition wins",
        "mathematics competition wins",
        "science fair awards",
        "debate competition wins",
        "writing competition wins",
        "publications",
        "exhibitions",
        "performances",
        "patents",
        "certifications",
        "scholarships",
        "grants",
        "awards",
        "recognition",
        "special projects",
        "startups",
        "business ventures",
        "charity work",
        "social initiatives",
        "environmental initiatives",
        "philanthropic work",
        "fundraising efforts",
        "community building",
        "social media influence"
    ]

    export const interests= [
        "science",
        "anatomy",
        "psychology",
        "media and communications",
        "video editing",
        "history",
        "literature",
        "writing",
        "sociology",
        "politics",
        "music",
        "art",
        "photography",
        "fashion",
        "design",
        "technology",
        "gaming",
        "sports",
        "cooking",
        "traveling",
        "nature",
        "animals",
        "space",
        "philosophy",
        "culture",
        "languages",
        "education",
        "health",
        "fitness",
        "finance",
        "business",
        "entrepreneurship",
        "leadership",
        "innovation",
        "creativity",
        "social media",
        "volunteering",
        "community service",
        "human rights",
        "environmental sustainability"
    ]

    export const non_technical_interests = [
        "mathematics",
        "physics",
        "chemistry",
        "management",
        "entrepreneurship",
        "economics",
        "law",
        "medicine",
        "geography",
        "architecture",
        "history",
        "literature",
        "writing",
        "sociology",
        "politics",
        "music",
        "art",
        "photography",
        "fashion",
        "design",
        "technology",
        "gaming",
        "sports",
        "cooking",
        "traveling",
        "nature",
        "animals",
        "space",
        "philosophy",
        "culture",
        "languages",
        "education",
        "health",
        "fitness",
        "finance",
        "business",
        "entrepreneurship",
        "leadership",
        "innovation",
        "creativity"
    ] 
    
    export const technical_interests = [
        "coding",
        "problem solving",
        "logical thinking",
        "statistics",
        "ux/ui",
        "data analysis",
        "machine learning",
        "artificial intelligence",
        "robotics",
        "cybersecurity",
        "networking",
        "cloud computing",
        "web development",
        "mobile app development",
        "game development",
        "database management",
        "software testing",
        "algorithm design",
        "mathematics",
        "physics",
        "chemistry",
        "biology",
        "electronics",
        "mechanics",
        "digital logic design",
        "computer architecture",
        "operating systems",
        "data visualization",
        "natural language processing",
        "computer vision",
        "big data",
        "blockchain",
        "IoT",
        "AR/VR",
        "3D printing",
        "quantum computing",
        "bioinformatics",
        "computational biology",
        "geographic information systems",
    ]